all:
	node runtests.js

meta:
	node -e 'require("./test_meta.js"); UnitTest.run(Test)'

primitives:
	node -e 'require("./test_primitives.js"); UnitTest.run(Test)'

base:
	node -e 'require("./test_base.js"); UnitTest.run(Test)'

util:
	node -e 'require("./test_util.js"); UnitTest.run(Test)'
